-- Script para crear la tabla de cuentas y billeteras operativas
CREATE TABLE IF NOT EXISTS public.operator_assets (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    operator_id uuid references auth.users(id) on delete cascade not null,
    type text not null,
    name text not null,
    value text not null,
    extra_info text
);

-- Habilitar RLS
ALTER TABLE public.operator_assets ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Users can view their own assets" ON public.operator_assets FOR SELECT USING (auth.uid() = operator_id);
CREATE POLICY "Users can insert their own assets" ON public.operator_assets FOR INSERT WITH CHECK (auth.uid() = operator_id);
CREATE POLICY "Users can update their own assets" ON public.operator_assets FOR UPDATE USING (auth.uid() = operator_id);
CREATE POLICY "Users can delete their own assets" ON public.operator_assets FOR DELETE USING (auth.uid() = operator_id);
