-- Script para crear la tabla de tareas persistentes del Dashboard
CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    text text not null,
    done boolean default false,
    operator_id uuid references auth.users(id) on delete cascade
);

-- Habilitar RLS
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Users can view their own tasks" ON public.tasks FOR SELECT USING (auth.uid() = operator_id);
CREATE POLICY "Users can insert their own tasks" ON public.tasks FOR INSERT WITH CHECK (auth.uid() = operator_id);
CREATE POLICY "Users can update their own tasks" ON public.tasks FOR UPDATE USING (auth.uid() = operator_id);
CREATE POLICY "Users can delete their own tasks" ON public.tasks FOR DELETE USING (auth.uid() = operator_id);
