-- Script para crear la tabla de enlaces operativos
CREATE TABLE IF NOT EXISTS public.operator_links (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    operator_id uuid references auth.users(id) on delete cascade not null,
    title text not null,
    url text not null,
    icon text default 'link'
);

-- Habilitar RLS
ALTER TABLE public.operator_links ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Users can view their own links" ON public.operator_links FOR SELECT USING (auth.uid() = operator_id);
CREATE POLICY "Users can insert their own links" ON public.operator_links FOR INSERT WITH CHECK (auth.uid() = operator_id);
CREATE POLICY "Users can update their own links" ON public.operator_links FOR UPDATE USING (auth.uid() = operator_id);
CREATE POLICY "Users can delete their own links" ON public.operator_links FOR DELETE USING (auth.uid() = operator_id);
