/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': '#0d1515',
        'outline': '#849495',
        'primary': '#dbfcff',
        'surface-tint': '#00dbe9',
        'surface-dim': '#0d1515',
        'on-tertiary-fixed': '#231b00',
        'on-primary-container': '#006970',
        'secondary-fixed': '#f8d8ff',
        'on-background': '#dce4e5',
        'on-tertiary-container': '#715d00',
        'secondary': '#ecb2ff',
        'surface-container-highest': '#2e3637',
        'on-primary-fixed': '#002022',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-high': '#232b2c',
        'surface': '#0d1515',
        'on-secondary-container': '#480063',
        'surface-variant': '#2e3637',
        'on-secondary-fixed-variant': '#74009f',
        'tertiary-container': '#fed639',
        'secondary-container': '#cf5cff',
        'outline-variant': '#3b494b',
        'on-primary': '#00363a',
        'on-error': '#690005',
        'on-secondary-fixed': '#320047',
        'inverse-surface': '#dce4e5',
        'inverse-primary': '#006970',
        'on-surface': '#dce4e5',
        'error-container': '#93000a',
        'on-surface-variant': '#b9cacb',
        'primary-fixed': '#7df4ff',
        'surface-container': '#192122',
        'on-secondary': '#520071',
        'primary-container': '#00f0ff',
        'tertiary': '#fff5de',
        'on-tertiary-fixed-variant': '#554500',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#00dbe9',
        'inverse-on-surface': '#2a3233',
        'surface-bright': '#333b3b',
        'surface-container-lowest': '#080f10',
        'on-tertiary': '#3b2f00',
        'secondary-fixed-dim': '#ecb2ff',
        'tertiary-fixed': '#ffe179',
        'tertiary-fixed-dim': '#eac324',
        'surface-container-low': '#151d1e',
      },
      fontFamily: {
        'body-base': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'code-label': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-base': ['16px', { lineHeight: '1.6', letterSpacing: '0px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '700' }],
        'code-label': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      spacing: {
        'gutter': '24px',
        'margin': '32px',
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
